### ISSUE TITLE
osx make failed

### ISSUE THREAD

**Issue by jonnywang** [redis/hiredis#431]
```
cc -std=c99 -pedantic -c -O3 -fPIC  -Wall -W -Wstrict-prototypes -Wwrite-strings -g -ggdb  net.c
net.c:139:37: error: use of undeclared identifier 'TCP_KEEPALIVE'
    if (setsockopt(fd, IPPROTO_TCP, TCP_KEEPALIVE, &val, sizeof(val)) < 0) {
                                    ^
net.c:433:29: error: use of undeclared identifier 'AF_LOCAL'
    if (redisCreateSocket(c,AF_LOCAL) < 0)
                            ^
net.c:458:21: error: use of undeclared identifier 'AF_LOCAL'
    sa.sun_family = AF_LOCAL;
                    ^
3 errors generated.
make: *** [net.o] Error 1
```

/usr/include/netinet  exists

clang -v

```
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by xor-gate** [comment]
Should be fixed by PR #433

**Comment by wanyue1215** [comment]
make is still fail in osx;
 error: use of undeclared identifier 'TCP_KEEPALIVE';
in osx , use 'SO_KEEPALIVE' instead of 'TCP_KEEPALIVE'

**Comment by jonnywang** [comment]
@wanyue1215 

https://github.com/redis/hiredis/commit/09e06f7dba19dfc243bf33497b282d27008ecb6c
https://github.com/redis/hiredis/commit/4b93e0db06df2a7565f088b661b58a9adc0cbfe6

can fixed

**Comment by xor-gate** [comment]
Why are we closing this issue while it is not fixed/merged?

**Comment by jonnywang** [comment]
sorry

**Comment by amallia** [comment]
We can close this.
