### ISSUE TITLE
Invalid OOM handling in async.c

### ISSUE THREAD

**Issue by oshamash** [redis/hiredis#640]
Already fixed this and added features at https://github.com/redis/hiredis/pull/638

Opening a ticket to enable proper conversation about whether it is actually needed.

**Comment by mnunberg** [comment]
I don't know if the handling is invalid

**Comment by michael-grunder** [comment]
Closing this issue since we fixed the UB via #754

**Comment by oshamash** [comment]
@michael-grunder that didn't fix the issue since some functions like `callbackValDup` still use the value allocated without checking for NULL

**Comment by michael-grunder** [comment]
[hi_malloc](https://github.com/redis/hiredis/blob/0184caac9de25258b23156016b3528e9878f1dae/alloc.c#L35) and other variants call an OOM handler on failure (defaults to [abort()](https://github.com/redis/hiredis/blob/0184caac9de25258b23156016b3528e9878f1dae/alloc.h#L36))

**Comment by oshamash** [comment]
@michael-grunder ok then, seems legit enough.
Also, any idea if you want #638 in the code anytime soon (should I invest some time rebasing properly ?)

**Comment by michael-grunder** [comment]
I'll take another look at the PR in the morning.

We may need to wait until after 1.0.0 though because we plan on releasing that soon.
